### ISSUE TITLE
mp3ファイルアップロード用ダイアログ

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#101]
校歌などのmp3をアップロードしやすいように、WYSIWYGにmp3アップロードボタンを作る。

**Comment by akagane99** [comment]
mp3アップロードは既に機能ありますが、それじゃダメな感じですかね？
![音楽１](https://user-images.githubusercontent.com/2756509/143153995-704bd8b4-1575-4113-9399-0e742545fa63.jpg)
![音声2](https://user-images.githubusercontent.com/2756509/143154001-43af77ec-f149-479e-ad7b-2336cc2c7ada.jpg)
![音声3](https://user-images.githubusercontent.com/2756509/143154006-a0cdc686-63e4-4e0d-af7b-c4df19593e6a.jpg)
![image](https://user-images.githubusercontent.com/2756509/143154015-e8ab5d90-eaed-477c-9fe2-7da4d4bd9eef.png)

**Comment by nagasheep** [comment]
まーじか。それでイケるのね。
機能的にはそれでOKですね。
説明とかを充実させればよいのか。

**Comment by akagane99** [comment]
> 説明とかを充実させればよいのか。

おす。その通りかと。
wysiwygのマニュアルに動画・音声の説明が無かったので、追加すればいいかと思います。
https://connect-cms.jp/manual/common/wysiwyg

**Comment by nagasheep** [comment]
サンキュー。
このスレッドは説明などの追加用にしよう。

**Comment by akagane99** [comment]
了解です。
それでは、wysiwygのマニュアルに動画・音声の説明を追加しときます。（機能追加時にマニュアル追記わすれのため）

**Comment by akagane99** [comment]
マニュアルに追記しました。クローズします。
https://connect-cms.jp/manual/common/wysiwyg/movie-audio
