### ISSUE TITLE
アップロードしたけど使用していないファイルや記事の削除

### ISSUE THREAD

**Issue by O-Masa** [opensource-workshop/connect-cms-ideas#107]
画像を張り付けるなどしてアップロードしたファイル、
アップロードファイル一覧には出てくるけど、削除できないので、
削除できるようになるとサーバーの健康状態を保つのによいかも。
（そもそもアップする前に気を付けよう！）
このあたりも関係するのかな？
https://github.com/opensource-workshop/connect-cms-ideas/issues/102

**Comment by masaton0216** [comment]
下記と重複した要求かと思いますので、本Issueはcloseします。
https://github.com/opensource-workshop/connect-cms-ideas/issues/73
