### ISSUE TITLE
【スライドショー】アップした画像の大きさが違う時に、画面が上下に動いてしまうのをなんとかして欲しい

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms-ideas#109]
スライダーに、縦横比が違う画像をアップした時、横幅に合わせれてしまう。
その為、縦が長い画像が表示された時、画面が上下する。
ブログや固定記事等を編集している時に、画面が動かれてしまうため、誤作動の元となってしまう。

アップされた画像の縦横比を合わせて欲しい。（画像を引き延ばすのではなく。上下に空白を入れる等して）

**Comment by gakigaki** [comment]
@osws-makino 
スライドショーの高さを設定できるようにするのはどうでしょうか？
現在のスライドショーは高さが画像ごとに変わってしまうため、この事象が発生しています。
高さ固定でこの事象は解決されますし、画面デザインもしやすいかと思います。

**Comment by osws-makino** [comment]
なるほど、です。
良いかも。

**Comment by gakigaki** [comment]
slideshow_heightブランチで作ってみたので、
動きを確認していただけますか？

**Comment by osws-makino** [comment]
はーい！　今確認中です！！

**Comment by gakigaki** [comment]
対応済みです。
