### ISSUE TITLE
データベースプラグインで、 データ型 double (8バイトの倍精度浮動小数点実数)で、数値入力可能にしていただきたいです。

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms-ideas#11]
データベースプラグインで、 データ型 double (8バイトの倍精度浮動小数点実数／（地図情報の緯度経度を入力したい）)で、数値入力可能にしていただきたいです。
用途は、googlemapに独自のマーカーを立てるときに、データベースに地図情報の緯度経度を登録して、利用したいです。

**Comment by akagane99** [comment]
「１行文字列型」にそのまま (8バイトの倍精度浮動小数点実数)を登録で、出来ないかな？

**Comment by dreamer9999** [comment]
akagane99さん、ご回答、ありがとうございます。
実際に試してみましたら、「１行文字列型」にそのまま (8バイトの倍精度浮動小数点実数)を登録でき、googlemapに独自のマーカーを立てることができました。
解決しましたので、closeさせていただきます。
（私がcloseしていいのかなあ？）

**Comment by akagane99** [comment]
> （私がcloseしていいのかなあ？）

もちろん^^
