### ISSUE TITLE
「タブ」プラグインで使う「データベース」プラグイン・「フォトアルバム」プラグイン

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms-ideas#125]
「タブ」プラグインで、

・現在、「データベース」プラグインの一覧表示のあと、詳細ボタンをクリックすると、詳細画面が出ないで
　「タブ」の先頭ページに戻る。
　今後、「タブ」の先頭ページに戻らないで、詳細画面が表示されるようになると、一層、使い勝手がよくなると思いますがいかがなものでしょうか。
　
・現在、「フォトアルバム」も同様に、アルバムをクリックすると、写真が出ないで、
　「タブ」の先頭ページに戻る。
　今後、「タブ」の先頭ページに戻らないで、写真が表示されるようになると、一層、使い勝手がよくなると思いますがいかがなものでしょうか。　

今後、何かのご参考になればと思い、記載させて頂きました。
（理論的に無理筋なことを言っているかもしれません、その際は、素人に免じてお許しください）

参考[ https://github.com/opensource-workshop/connect-cms/issues/1092]( https://github.com/opensource-workshop/connect-cms/issues/1092)

**Comment by nagasheep** [comment]
こんにちは。
永原です。

タブ・プラグインは現状は、初期画面を表示します。
いろいろな機能があれば便利だとは思いますが、現状、そこに費用をかけることはできません。
（機能を作る＝人が動く＝費用が掛かる。ということになります）

いつか、機能を増やせると良いなとは思いますが、現状は予定しません。
どっかから費用が出るとか、プログラムの改造をソースコードで提案していただければ、よろこんで検証します。

ということで、ご理解いただければ、一旦このIssueeはCloseしてください。

マニュアルには反映するようにしますね。（すぐは作業時間が取れないですけど）

以上

**Comment by dreamer9999** [comment]
永原様

いつもありがとうございます。
一旦、このIssueeはcloseします。
