### ISSUE TITLE
【固定記事】もっと見る機能の追加

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms-ideas#129]
## 背景

・学校のお客様よりトップページの固定記事が長くなってしまったため、「もっと見る」機能は使えないかと問合せあり。
　「もっと見る」機能で記事をスッキリさせたいとの事でした。
・固定記事に「もっと見る」機能は現状無いため、１記事だけのブログを作ってもらい「もっと見る」機能を使ってもらいました。

## 対応案

ブログに「もっと見る」機能実装済みなので、固定記事にその機能を移植して欲しいなぁ。

## 参考：ブログ

![image](https://user-images.githubusercontent.com/2756509/162152408-3e7d6a76-d5a3-4704-8867-93496ac82f8b.png)

![image](https://user-images.githubusercontent.com/2756509/162152559-789647d1-9a4f-46de-9529-477b99bef1eb.png)

## 固定記事（2022/4/7現在）

![image](https://user-images.githubusercontent.com/2756509/162152110-7b399981-691b-4771-ad66-94628dcaab2e.png)

**Comment by nagasheep** [comment]
そうそう。
やりたいのよ。
実は、テーブルには、カラムは持っています。（笑）

**Comment by akagane99** [comment]
今後対応してあげたいねぇ。

**Comment by akagane99** [comment]
対応済みです。
