### ISSUE TITLE
ウィジウィグで画像アップ時にサイズ指定でリサイズしたい

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms-ideas#15]
## リサイズ
サイズ指定。
・原寸
・大
・中
・小
・極小

TinyMCE の画像プラグイン、改造しちゃう
＋
サーバでのリサイズ処理。（いまのところGD）

・登録時のみ

## 他

・画像の回転の自動判定

**Comment by nagasheep** [comment]
ウイルスチェック？（^^）

**Comment by akagane99** [comment]
入力補完ミス💦

**Comment by akagane99** [comment]
リサイズ処理は下記で対応済み。
https://github.com/opensource-workshop/connect-cms/issues/843#issuecomment-842285807

**Comment by gakigaki** [comment]
リサイズ処理は対応済みのため、クローズします。

以下の点については、別issueに上げる。
- サイズ選択
- 画像の回転の自動判定

**Comment by akagane99** [comment]
> 以下の点については、別issueに上げる。
> 
> サイズ選択


・TinyMCE の画像プラグイン、改造方法がわかったため「サイズ指定」を入れて対応する。
　・初期サイズ指定を、サイト管理に追加して設定できるようにする。
・別issueが無かったため、再オープンしてここで管理する。

**Comment by akagane99** [comment]
・TinyMCE の画像プラグイン、改造方法ファイル

[plugin.min.js.txt](https://github.com/opensource-workshop/connect-cms-ideas/files/7248143/plugin.min.js.txt)

**Comment by akagane99** [comment]
対応しました。

* TinyMCE の画像プラグイン
    * 「画像サイズ」追加（リサイズ用）
         *  `GD`が無効な場合表示しないように対応
    * 画像アップロード時に、幅・高さを自動セットしないよう修正（原寸サイズが自動セットされるため、リサイズで小さくしても大きく表示される不都合があるため）
    * アップロードできる１ファイルの最大サイズの説明を、「画像のソース」の下に移動
    * Alternative description ⇒ 代替テキスト に表示修正
* WYSIWYG設定
    * 「初期に選択させる画像サイズ」追加
         *  `GD`が無効な場合、無効になる＋注意メッセージを表示

## 修正後画面
### TinyMCE の画像プラグイン
![image](https://user-images.githubusercontent.com/2756509/135208416-d6a9298d-7df2-4c68-a3c4-8ba76b7f7ba3.png)

### サイト管理＞その他設定＞WYSIWYG設定
![image](https://user-images.githubusercontent.com/2756509/135222797-73744044-6ccb-406a-bda6-46e19a30d71b.png)

## GD無効時
### TinyMCE の画像プラグイン
「画像サイズ」を表示しない
![image](https://user-images.githubusercontent.com/2756509/135223228-f7a15551-b6de-48a5-81d9-7f2953be72ca.png)

### サイト管理＞その他設定＞WYSIWYG設定
「初期に選択させる画像サイズ」無効になる＋注意メッセージを表示
![image](https://user-images.githubusercontent.com/2756509/135223421-9db89981-6470-41a2-a6b9-865397627fb0.png)


## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/678a1bc9014c59b63fe201e20168c9721f30eed8
https://github.com/opensource-workshop/connect-cms/commit/57bc1cb4ed1a5435b39f0884db57cf3204020de9
https://github.com/opensource-workshop/connect-cms/commit/82272abfd325a6bf93891a4da9bf77d62da432d8

**Comment by akagane99** [comment]
## 残作業
- [x] オンラインドキュメントの修正
https://connect-cms.jp/manual/manager/site#frame-380
https://connect-cms.jp/manual/common/wysiwyg/image

**Comment by akagane99** [comment]
対応済み
