### ISSUE TITLE
[フォーム] 画像認証（CAPTCHA）の導入

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms-ideas#153]
NC2/NC3でもあった画像認証（CAPTCHA）を導入したいな

# 参考程度

* LaravelでCAPTCHAを導入してみる - Qiita
https://qiita.com/niisan-tokyo/items/3ef39d2bf6883a4a5789
* 該当ライブラリ
https://github.com/mewebstudio/captcha

**Comment by masaton0216** [comment]
クライアントから要望があったのでちょいと調べた内容と私見もぶら下げておきます。

# 参考（井上私見）
## 結論
 - 現時点でもCAPTCHAの有用性がないか、と問われるとそこまでは感じられない（CAPTCHAがあるだけでもボット対策としては有用な印象）為、ユーザ目線での機能のシンプルさから「まずはCAPTCHA導入」でもいいような気もします。
## 参考（CAPTCHAとreCAPTCHAの違い）
> reCAPTCHAは、Googleの提供する無料サービスで、従来のCAPTCHAを置換するものです。
>reCAPTCHAは、一般的なCAPTCHAテストよりも高度です。CAPTCHAと同様に、一部のreCAPTCHAでは、ユーザーはコンピューターでは解読困難なテキストの画像を入力する必要があります。通常のCAPTCHAとは異なり、reCAPTCHAは実世界の画像からテキストを取得します。住所の写真、書物の文字、古い新聞の文字などです。

https://www.cloudflare.com/ja-jp/learning/bots/how-captchas-work/

## reCAPTCHAについて
 - Google側の設定（ユーザによる設定）も必要なのが、少しネック（メンドイ、人によってはわからない等）かなとは思います。
     - reCAPTCHA：よく見る「バイクを選べ」等の3×3のマス目パズルみたいなやつも使えるGoogle製サービス
 - 一方で、Google側による機能更新の恩恵を受けられそうな（機能的に陳腐化しない）期待もあります。

## CAPTCHAについて
 - ユーザ目線でシンプルで使いやすそうな印象（フォームプラグインの設定画面で機能On/Offするだけ）は持てます。
     - 懸念（機能的に陳腐化する懸念がある）
         - ボットがOCR技術を以って、さらにそのOCRが進化した場合は突破される可能性
             - 2021年時点でTRYした記事。突破は出来なかったっぽいので、まだまだ平気そうな印象ではありますが： https://qiita.com/N_KS/items/2373502d0546ac5e6b84
         - テキスト入力オンリーなCAPTCHAの場合、ブルートフォース対策で突破される可能性

## 参考（reCAPTCHAのv2とv3の違い）
https://qiita.com/koseki/items/a2436b831afcdf73b946 

## 参考（LaravelでreCAPTCHA（v2））
https://qiita.com/pop-culture-studio/items/f731387b433d8fb2f40c 

## 参考（LaravelにreCAPTCHA (v3) を導入する）
https://zenn.dev/babyjob/articles/laravel-recaptcha-v3 

## 参考（LaravelでCAPTCHAを導入してみる）※≠「reCAPTCHA」
https://qiita.com/niisan-tokyo/items/3ef39d2bf6883a4a5789

**Comment by masaton0216** [comment]
余談ですが、最近はこんなものもあるようです。ムズイ（笑）
![image](https://github.com/opensource-workshop/connect-cms-ideas/assets/13323806/99aa4eee-9c47-4251-b1c5-29fdb4b08029)

**Comment by akagane99** [comment]
対応済み
