### ISSUE TITLE
WYSIWYG のPDF アップロードプラグイン

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#16]
【要望】
PDFアップロード時に以下の動きを実現したい。
・サムネイル画像が自動で生成される。
・サムネイルの下にはファイル名が表示される。
・サムネイル、ファイル名ともにリンクが張られる。（targetはblank）
┌───────┐
│サムネイル│
└───────┘
ファイル名

【使用する技術の調査】
ImageMagick＋Ghostscript を使う方法、Xpdf を使う方法など、複数の方法があるようです。
どの方法が良いか、調べる必要がある。

【提供方法：変換サービス（共通）】
サーバ側にPHP 以外のソフトウェアをインストールする必要が出てくるため、以下の方法で実装を検討したい。
・画面はWYSIWYG のプラグインとして実装する。
・このプラグインを表示するか否かの判断は.env に記述する。（デフォルトはOFF）
・Connect-CMS とは別に、「PDF to 画像変換のサービス」があるものとして考える。
　（レンタルサーバなどで、自由にサーバを設定できないケースもあると思うため、外部サービスを呼ぶ形式にする）
・Connect-CMS のWYSIWYG の「PDF アップロードプラグイン」から呼び出す「PDF to 画像変換のサービス」のURL はソースに埋め込むのではなく、.env で記述する。
・「PDF to 画像変換のサービス」に関しては、インターフェース仕様を公開する。（開発しようと思えばできるところまでは提供する）
・「PDF to 画像変換のサービス」のインターフェース仕様には、サイトを認証するサイトコードとtoken なども設計する。

【提供方法：変換サービス（有料）】
・株式会社オープンソース・ワークショップにPDF to 画像変換のサービスを用意する。
・株式会社オープンソース・ワークショップで提供するConnect-CMSクラウド（有料のConnect-CMSサービス）では、上記の「PDF to 画像変換のサービス」を呼ぶ。
・サイトコードとtoken などは.env に記述する。

【提供方法：変換サービス（無料）】
・「PDF to 画像変換のサービス」のインターフェース仕様を公開するので、無料で実施したい場合は、自分で「PDF to 画像変換のサービス」を実装すれば良い。

**Comment by nagasheep** [comment]
以前、Issue に書いていたものも、こちらに転載。

https://github.com/opensource-workshop/connect-cms/issues/339
・サムネイル数の設定（サイト設定で基本数、ファイルアップロードで個別の数（複数ファイル指定の下で指定することで、アップロードするアクション単位で設定できるなど））
・パスワード付きPDF の場合はサムネイル生成がエラーになるので、サムネイルを出力しない。
・可能ならパスワードも入力して、パスワード付きPDF もサムネイル生成

**Comment by akagane99** [comment]
調査メモ

* Xpdf
  * コマンドでpdfからサムネイル作成のみ。サーバサイド。
        * [参考記事：超簡単！ Xpdfを使ってPDFからサムネイル画像を作る方法](https://tech.arms-soft.co.jp/entry/2020/03/25/090000)
  * インストール
      *   (サーバにインストール)
        *  `sudo yum install - y xpdf`
      * phpからは `exec()` で実行
      * 要確認
        * ただ、Xpdfはリサイズが得意ではないようです。試した限りでは、かなりガタガタになりました。
  * [公式サイト](https://www.xpdfreader.com/index.html) 
    * Current version: 4.03 Released: 2021/1/28
  * [ウィキペディア](https://ja.wikipedia.org/wiki/Xpdf)
  * 脆弱性件数：123件 (2021/7/16時点) [情報源](https://jvndb.jvn.jp/search/index.php?mode=_vulnerability_search_IA_VulnSearch&lang=ja&keyword=xpdf+&useSynonym=1&vendor=&product=&datePublicFromYear=&datePublicFromMonth=&datePublicToYear=&datePublicToMonth=&dateLastPublishedFromYear=&dateLastPublishedFromMonth=&dateLastPublishedToYear=&dateLastPublishedToMonth=&cwe=&searchProductId=)
* Poppler
  * Xpdfからフォークライブラリ
  * PDFからテキストを抽出する `pdftotext` コマンドは、このライブラリを入れる記事が多そう。
    * インストール
        *   (サーバにインストール)
          * `yum install poppler-utils`
  * PDFからサムネイル作成は `pdftoppm -jpeg hoge.pdf hoge` コマンドでいける。
  * https://ja.wikipedia.org/wiki/Poppler
  * https://blog.taka.at/archives/53390219.html
*  imagemagick+ghostscript
    * サーバサイド。参考記事多い。
        * [簡単便利！PHPでPDFをテキスト＆画像ファイルに変換する方法](https://blog.capilano-fw.com/?p=1756)
    * インストール
        *   (サーバにインストール)
          * `sudo yum install ghostscript`
          * `sudo yum install ImageMagick`
          * Imagick (php関数)
        *   (phpライブラリ)
          * `composer require spatie/pdf-to-image` https://github.com/spatie/pdf-to-image
    * [公式サイト](https://imagemagick.org/index.php)
        *  Release: 7.1.0-2  - 2021年6月25日
    * [ウィキペディア](https://ja.wikipedia.org/wiki/ImageMagick)
    * 脆弱性件数：572件 (2021/7/16時点) [情報源](https://jvndb.jvn.jp/search/index.php?mode=_vulnerability_search_IA_VulnSearch&lang=ja&keyword=imagemagick&useSynonym=1&vendor=&product=&datePublicFromYear=&datePublicFromMonth=&datePublicToYear=&datePublicToMonth=&dateLastPublishedFromYear=&dateLastPublishedFromMonth=&dateLastPublishedToYear=&dateLastPublishedToMonth=&cwe=&searchProductId=)
*  Gd+ghostscript
    * サーバサイド。参考記事ほぼない。
        * [/phpでpdfドキュメントをプレビューイメージに変換するにはどうすればよいですか？](https://www.it-swarm-ja.com/ja/php/phpでpdfドキュメントをプレビューイメージに変換するにはどうすればよいですか？/958219677/)
         * https://www.sunapro.com/pdf-to-jpeg/
    * インストール
        *   (サーバにインストール)
          * `sudo yum install ghostscript`
          * `Gd`
      * phpからは `exec()` でgsコマンド実行
      * ` exec('gs -dSAFER -dBATCH -sDEVICE=jpeg -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r300 -sOutputFile=whatever.jpg input.pdf') `
 *  ImageMagick+gsその2
    * サーバサイド。
        * [/phpでpdfドキュメントをプレビューイメージに変換するにはどうすればよいですか？](https://www.it-swarm-ja.com/ja/php/phpでpdfドキュメントをプレビューイメージに変換するにはどうすればよいですか？/958219677/)
    * インストール
        *   (サーバにインストール)
          * `sudo yum install ImageMagick`
          * `sudo yum install ghostscript`
      * phpからは `exec()` でconvertコマンド実行
      * ` exec("convert pdf_doc.pdf image.jpg"); `
    * 参考
      * https://atmarkit.itmedia.co.jp/ait/spv/1809/25/news020_2.html
      * GhostScriptは、PostScriptの互換プログラムで、これを利用することでImageMagickはPDFファイルを扱えるようになる。
*  PDF.js
    * クライアント側。~~IE非対応~~。サムネイル対応の参考記事少ない。
      * ES5版（古いバージョン）を使えばie11いける。 [IE11でPDFを表示する - Qiita](https://qiita.com/kakita-yzrh/items/3761a6599c783284aa60)
      * [参考記事：Dropboxも採用！JSだけでPDFをレンダリングできるPDF.jsにしびれた！](https://www.webprofessional.jp/custom-pdf-rendering/)
      * [PDF.jsを使ってPDFをサムネイル表示させた](https://xpig.hatenablog.com/entry/2019/01/30/185323)
      * https://usefulangle.com/post/24/pdf-to-jpeg-png-with-pdfjs
    * インストール
      * (jsライブラリ)
        * `<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>` 
        * `pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://mozilla.github.io/pdf.js/build/pdf.worker.js';` 
      *  jsライブラリをダウンロードしてConnect-CMSに組込み。
    * [公式サイト](https://mozilla.github.io/pdf.js/)
      * v2.8.335 2021/4/5

**Comment by akagane99** [comment]
追加メモ

## 管理者メニュー対応
　外部サービス設定（システム管理権限）
　　・WYSIWYG設定
　　　・翻訳
　　　・【済】PDF

### PDFメニュー

・【済】初期に選択させるサムネイルの大きさ
　　選ばせる。（デフォルト=サムネイル）

・【済】初期に選択させるサムネイルの数
　選ばせる。４（デフォルト）

・【済】サムネイルのリンク
　　・PDFを開く（デフォルト）　・画像を開く

## ウィジウィグのPDF

・【済】翻訳の右となりにPDFアイコンもってく

・【済】PDFパスワードに対応

・【済】サムネイルの大きさ、選択可能
　長編だけ設定。

　画面のwidth(画像のpx)
　　1200(1200)※1, 800(800)※1, ~~400~~ 320(400)※2, 200(200)※3, 150(200)※4
　　大、中、小、極小、サムネイル
　　※1 左・中央エリア表示で、中央エリアのwidthはmax680px位。そのため、横並び１枚表示。
　　※2 左・中央エリア表示で、中央エリアにサムネイルを並べた時、横並びで2枚まで表示
　　※3 同上の条件で、横並びで3枚まで表示
　　※4 同上の条件で、横並びで4枚まで表示

・【済】サムネイルの数、選択可能
　選択肢：　１，２，３，４、全て

・【済】APIキーは、APIサービス側DBで管理

## ※ PDF画像化ライブラリはPopplerを採用
　・PDFからテキストを抽出する `pdftotext` コマンドを別件で使う
　・PopplerはXpdf派生のライブラリで、PDF画像化も行えるため。`pdftoppm -jpeg hoge.pdf hoge`

**Comment by akagane99** [comment]
対応しました。

>　外部サービス設定（システム管理権限）
　　・WYSIWYG設定
　　　・翻訳

上記は別issueとして検討します。


* WYSIWYG のPDF アップロードプラグインの追加 
* 画像のURLをブラウザで直接開いた場合、ブラウザで表示するよう変更（'png','jpg','jpe','jpeg','gif'） ※いままではダウンロード動作。

### 設定ファイル
WYSIWYG のPDF アップロードプラグインを使用するには、設定ファイルに外部サービス設定が必要です。
設定ファイル：`.env`の `PDF_THUMBNAIL_API_URL`, `PDF_THUMBNAIL_API_KEY`


## 修正後画面
### WYSIWYG のPDF アップロードプラグイン（新規追加）
![image](https://user-images.githubusercontent.com/2756509/134100102-2fa73998-2963-4839-967b-0f253e52edc5.png)
![image](https://user-images.githubusercontent.com/2756509/134100156-762657cf-b4a8-41b2-a1e8-02ea1c0e2a6c.png)
※ 例）PDF２ページの「template.pdf﻿」をアップロードした場合
![image](https://user-images.githubusercontent.com/2756509/134100199-ed9f81c4-a6f5-4e19-a221-0ced0d98617b.png)

### 外部サービス設定＞WYSIWYG設定（新規追加）

![image](https://user-images.githubusercontent.com/2756509/134100544-8bcbb325-3f23-4f54-a53f-d16bd0b9c7e3.png)
※ `.env` の `PDF_THUMBNAIL_API_URL` 設定時のみ設定可能。

### 外部サービス設定＞PDFアップロード（新規追加）

![image](https://user-images.githubusercontent.com/2756509/134100617-974682a3-2ecb-4d50-985a-ac0333c1dd70.png)
※ `.env` の `PDF_THUMBNAIL_API_URL` 設定時のみ設定可能。



## 修正プログラム

https://github.com/opensource-workshop/connect-cms/pull/984/files
