### ISSUE TITLE
Github Actionsで古いissue, プルリクエストは自動で閉じたい

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms-ideas#21]
要検討
issueとかの整理を定期的に行っていないので、一定期間activeでないissueは、自動クローズでいいんじゃないかと。
もし必要な古いissueがクローズされたら再オープンする感じで、古いissue整理が進むのかなと。

https://github.com/actions/starter-workflows/blob/055373ee0b531de9b779896c520d0555e7df48ae/automation/stale.yml

自動label付与もされるっぽい。
```yml
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
```

## 参考URL

https://tech.pepabo.com/2021/03/03/ec_efficiency_with_github_actions/

**Comment by nagasheep** [comment]
そんなのできるのね。
賛成。

**Comment by akagane99** [comment]
まずはアイデアリポジトリで対応しました。
⇒ Connect-CMS本体も対応しました。

テンプレが用意されてるので、設定らくちんでした。

* 毎日AM1時に実行（UTC 16時）
* issueのみ実行
  * 1年更新なかったら「close予定」ラベル付与＆メッセージ自動投稿
  * その後1ヵ月で自動close
  * closeしたくなかったら、「close予定」ラベル外すか「自動close除外」ラベル付ける。

とりあえず自動closeする期間を、現状を踏まえて１年で設定。
もし見直したかったら、今後見直しする方向で。

プルリクエストは現状、放置されているものがないので、今回は対象外としました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms-ideas/commit/b3022a177c008af323bbd06bba57523e5122c870
https://github.com/opensource-workshop/connect-cms/commit/f5cdf6aa8a45d1e292acfb59cc8458806eeebab4

**Comment by akagane99** [comment]
Connect-CMS本体も対応したので、クローズします。

**Comment by akagane99** [comment]
そういえばyaml に書いてあった　secrets.GITHUB_TOKEN　を発行してなかっけど大丈夫？
→大丈夫だった。

https://dev.classmethod.jp/articles/mapping-secrets-github-token/
> secrets.GITHUB_TOKEN | 発行の手間がいらない
