### ISSUE TITLE
テーマを通して反映されるCSSの指定がしたい。

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#23]
ページごとにテーマを変えた場合でも、各ページに反映されるCSSを指定したい。
サイト管理で指定する「テーマ」の下に、「追加で全体に反映するテーマ」の指定ができるようにする。
そうすることで、作成したユーザ・テーマを「追加で全体に反映するテーマ」に指定することで、全体のCSSが実現できる。

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/pull/861
上記で対応済みのため、クローズします。
