### ISSUE TITLE
機械翻訳の英語以外の対応

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#29]
WYSIWYG の機会翻訳は現在、英語のみだが、他の言語にも対応する。

**Comment by akagane99** [comment]
英語、ポルトガル語、フランス、ドイツ、スペイン、中国語（簡体、繁体）、韓国語

**Comment by akagane99** [comment]
対応しました。

## 修正後画面

![image](https://user-images.githubusercontent.com/2756509/123590530-b7902980-d825-11eb-8639-a856f2625725.png)

![image](https://user-images.githubusercontent.com/2756509/123590589-caa2f980-d825-11eb-9891-6bb9d2bd9f9a.png)


## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/cbff54bec096dd3c78edfb71a105b767a112647e

**Comment by akagane99** [comment]
・オンラインマニュアルを更新しました。
https://connect-cms.jp/manual/common/wysiwyg/translate

・Connect-CMS公式サイトを最新にアップデートしました。
https://connect-cms.jp/

**Comment by akagane99** [comment]
## 追加対応
ベトナム語

**Comment by akagane99** [comment]
ベトナム語対応しました。

## 修正後画面

![image](https://user-images.githubusercontent.com/2756509/123895370-b7656a80-d99a-11eb-9de0-4d88586a18d5.png)

![image](https://user-images.githubusercontent.com/2756509/123895235-7a00dd00-d99a-11eb-89c8-40a544e41458.png)


## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/a3e8f3d2976335dd0a7ddabe4e4bdaa5c3c79df1

**Comment by akagane99** [comment]
・Connect-CMS公式サイトを最新にアップデートしました。
https://connect-cms.jp/

**Comment by akagane99** [comment]
・オンラインマニュアルを更新しました。
https://connect-cms.jp/manual/common/wysiwyg/translate

**Comment by akagane99** [comment]
タガログ語（フィリピン語）対応

**Comment by nagasheep** [comment]
タガログ語が選択肢にでてこなかったんだけど、何か必要だっけ？
Connect-CMS公式サイトで確認しました。

**Comment by nagasheep** [comment]
あ、まだ作業してなかったのか。失礼。

**Comment by akagane99** [comment]
あ、すっかり忘れてました。対応します。

**Comment by akagane99** [comment]
タガログ語、対応しました。

## 対応後画面
![image](https://user-images.githubusercontent.com/2756509/130022254-5a5cde2c-c462-4de8-9fae-bed020dd6e01.png)
![image](https://user-images.githubusercontent.com/2756509/130022328-4550095c-6b42-4c01-acce-b4974be85c8c.png)

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/3dadd00b8be976fa7aa53e2fbd5d06e37bf7f582

**Comment by akagane99** [comment]
オンラインマニュアル更新しました。
https://connect-cms.jp/manual/common/wysiwyg/translate
