### ISSUE TITLE
データベース関連マニュアルへの説明追記のお願い

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms-ideas#38]
■「データベースプラグイン」

データベースへZIPファイル一括インポートについて,添付ファイル一括インポートなど
紹介されていますが、実際にどのように行えばいいかがわかりません。
※例えば、25000件などの大量のデータもZIPファイルにすれば、容易にインポートできる？
実際の具体例をあげて、マニュアルに説明を追記していただければ、
優れた機能を使えるようになるようになるのではないかと思います。

■「データベース検索プラグイン」

マニュアルがうまく理解できません。
実際の具体例をあげて、マニュアルに説明を追記していただければ、
優れた機能を使えるようになるのではないかと思います。

以上、今後の検討リストに載せていただければ、嬉しいです。

**Comment by nagasheep** [comment]
@dreamer9999 様へ
株式会社オープンソース・ワークショップの永原です。

25,000件のデータ、なかなか、大量データですね。
通常、Webシステムでは、大量データの操作は、エラーの原因になることが多くあります。
私の会社でなくても良いので、システムのプロにお金を払って委託するのが良いのではないかと思います。
もしくは、ご自分で、システムを学ばれるのも、方法かと思います。
お金を払って委託する、自分で勉強して解決する。これを選択できるのが、オープンソースの利点の一つです。
オープンソースは、あくまで、多くの人に役立ててもらえれば、という意味も込めて「公開しているもの」ですので、「要求を聞く」、ということとは別のものです。
そこをご理解いただければ幸いです。

**Comment by nagasheep** [comment]
株式会社オープンソース・ワークショップの永原です。

誤解を与えてはいけないと思うので、追記します。
当社の場合、有料サービスをご使用いただいているからと言って、要望をすべて聞く。というわけではありません。
ご要望がある場合は、実際のご利用方法や運用の状況をお伺いし、汎用的に必要な機能であると判断した場合には、Connect-CMSに取り込ませていただいております。

当社としては、Connect-CMSをお使いのユーザー様や事業者様に、具体的に最適な内容をご提案することを心がけております。

当社方針と異なることがご要望の場合も、もちろん、有ると思いますし、否定するつもりはございません。
そのための、オープンソースライセンスであり、カスタマイズも自由に行っていただけるものとして、公開しております。

以上、補足にて失礼いたします。

**Comment by dreamer9999** [comment]
永原様

いつも、ご丁寧なご説明をありがとうございます。
おっしゃっていることは、よくわかりました。
このissueはcloseさせていただきます。
