### ISSUE TITLE
カレンダーで日付の数字は折り返したくない。

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#4]
カレンダー表示が細いと、2桁の数字が折り返している。
![カレンダー](https://user-images.githubusercontent.com/3079435/116067266-f7bb1a80-a6c3-11eb-8a07-f43e8853bb55.png)

**Comment by masaton0216** [comment]
test

**Comment by nagasheep** [comment]
対応しました。
![image](https://user-images.githubusercontent.com/3079435/116324523-43241480-a7fb-11eb-9f56-a482f4347957.png)
