### ISSUE TITLE
データベースプラグインの表示横幅を、ピクセル値で指定できるようにしたい

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms-ideas#40]
※好き勝手なことを述べているようで、非常に気になっていますが、
connect-cmsの発展のため、参考にしていただけるアイデアが、少しかは含まれているかもしれない、と思い、記載させていただきました。

①
データベースプラグインの表示横幅を、ピクセル値で指定できれば、見栄えが増すかと思います。
下記レイアウトの場合、「picture」と「名前」の間が広く、見栄えがイマイチです。
それぞれの項目の横幅を、ピクセル値で指定できれば、思った通りのデザインができるかと思います。

![ＤＢ要望横幅](https://user-images.githubusercontent.com/3895089/120323987-0cbd4600-c321-11eb-860a-b5c6dd5344e5.png)

②
データベースプラグインの表示横幅の動きが、全角と半角では異なるみたいです。
動きを統一した方が、分かり易い気がします。
（半角の場合のみ、桁数が溢れると、下段に表示される）

![ＤＢ要望横幅数値](https://user-images.githubusercontent.com/3895089/120323923-ff07c080-c320-11eb-9769-c2173d0301bf.png)

**Comment by nagasheep** [comment]
@dreamer9999 様

こんばんは。
株式会社オープンソース・ワークショップの永原です。

Connect-CMSでは、基本的に、パソコンやスマートフォンなどの様々なデバイスに対応するため、ピクセル指定をすることは、いまのところ考えていません。

> ※好き勝手なことを述べているようで、非常に気になっていますが、
> connect-cmsの発展のため、参考にしていただけるアイデアが、少しかは含まれているかもしれない、と思い、記載させていただきました。

気にしていただき、ありがとうございます。
正直に申し上げます。
参考にできるアイデアより、我々の時間を使う方が、かなり多いです。
書いていただいたことを読んだり理解したり、社内で議論したりすることよって、我々の仕事の時間を奪われることでの良くない影響も心配される状況になってきたかと思っています。
必要でしたら、オフラインでお話ししたり、オンラインミーティングで話し合うことは、拒否するつもりはありません。
いつでも、必要な話し合いをする準備がありますので、連絡をいただければと思います。

以上、失礼いたします。
