### ISSUE TITLE
WYSIWYG で文字サイズの指定

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#41]
現在、WYSIWYG で文字サイズの指定ができません。
・要望として文字サイズの指定があること。
・サイトポリシーとして文字サイズ指定をさせたくないケースにも対応したい。
これらを実現させる方法として、サイト管理で文字サイズ指定を表示するかどうか、設定できるようにする。

**Comment by akagane99** [comment]
## 文字サイズ
・文字の大きさアイコンを 表示する/表示しない。 これだけ対応。
・Default Valueに準じた、~~em だか~~ rem サイズを設定する。（ptなどの絶対サイズ指定ではなく、emなどの相対サイズ指定でスマホ表示にも対応する）
　・%指定の方がわかりやすい？

https://www.tiny.cloud/docs/configure/editor-appearance/#fontsize_formats
> Default Value: '8pt 10pt 12pt 14pt 18pt 24pt 36pt'

```js
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'fontsizeselect',
  fontsize_formats: '8pt 10pt 12pt 14pt 16pt 18pt 24pt 36pt 48pt'
});
```

・Connect-CMSの標準文字サイズは 16px


px | pt | ％ | rem
-- | -- | -- | --
48 | 36 | 300% | 3
32 | 24 | 200% | 2
24 | 18 | 150% | 1.5
21.6 | 16.2| 135% | 1.35 ※4
21.3333| 16 | 133.3333% | 1.3333 ※4
20.8| 15.6 | 130% | 1.3 ※4★★★
19.2 | 14.4 | 120% | 1.2 ※1
18.6667| 14 | 116.6667% | 1.1667 ※1
115 | 13.8 | 115% | 1.15 ※1★★★
18 | 13.5| 112.5% | 1.125 ※1
16 | 12 | 100% | 1
13.6 | 10.2 | 85% | 0.85 ※2★★★
13.3333 | 10 | 83.3333% | 0.8333 ※2
13 | 9.75 | 81.25% | 0.8125 ※2
10.6667 | 8 | 66.6667% | 0.6667 ※3
10.4 | 7.8 | 65% | 0.65 ※3★★★
10 | 7.5 | 62.5% | 0.625 ※3

※1～4は、いずれかの値をチョイスする。

### 参考URL

CSS3のremとemの違いについて - Qiita
https://qiita.com/masarufuruya/items/bb40d7e39f56e6c25f0d

Font size conversion px-pt-em-rem-percent
https://websemantics.uk/tools/font-size-conversion-pixel-point-em-rem-percent/

font-sizeを指定するときに！ px・pt・％の数値一覧 - Qiita
https://qiita.com/tricolorebox/items/eda9a829c81c25dbb0de

Full featured examples | Docs | TinyMCE
https://www.tiny.cloud/docs/demo/full-featured/

## 小さい文字

・`<small>`タグを段落リストに追加する
・ツールバーのアイコンないか調査⇒ なかった。

### 参考URL

`<small>`: 附随コメント要素 - HTML: HyperText Markup Language | MDN
https://developer.mozilla.org/ja/docs/Web/HTML/Element/small

**Comment by akagane99** [comment]
小さい文字、対応しました。

## 修正後画面

![image](https://user-images.githubusercontent.com/2756509/121642393-6a912100-cacb-11eb-9813-062b3ed6f992.png)


## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/6878fc194884646d423b15ae786adffb14cd04c3

**Comment by akagane99** [comment]
対応しました。
文字サイズは下記で設定しました。

```js
fontsize_formats: '0.65rem 0.85rem 1rem 1.15rem 1.3rem 1.5rem 2rem 3rem',
```

あと、`resources\views\plugins\common\wysiwyg.blade.php` で`configs`を参照する必要があったため、
`app/Http/Middleware/ConnectInit.php` で全ビュー間のデータ共有として、全configsを`View::share('cc_configs', $configs)`に設定しました。

https://github.com/opensource-workshop/connect-cms/commit/962f0c215a24c79d36b2da829b6679da5acd4a37

## 修正後画面
### サイト管理＞WYSIWYG設定（新規追加）

![image](https://user-images.githubusercontent.com/2756509/121659009-d8921400-cadc-11eb-8cb9-a10d10b38821.png)

### WYSIWYG(文字サイズON)

![image](https://user-images.githubusercontent.com/2756509/121659270-18f19200-cadd-11eb-8dbc-a6aeecdfe4b3.png)


## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/820984d8a22540d59d7ab1bb77d7acd4253bfbbe

**Comment by akagane99** [comment]
オンラインマニュアル更新しました。

サイト管理（WYSIWYG設定）
https://connect-cms.jp/manual/manager/site#frame-380

WYSIWYG 文字サイズ
https://connect-cms.jp/manual/common/wysiwyg/fontsize

WYSIWYG 書式設定
https://connect-cms.jp/manual/common/wysiwyg/format#frame-148
