### ISSUE TITLE
ブログの表示件数：「表示件数」なので、設定するのはフレームに対しての方が良いのでは？

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms-ideas#56]
１つのブログを複数のページにて表示する時にふと気づきました。
配置するページよって表示件数を変更したいのに、今はブログ自身に表示件数を持ってしまっているので
別ページ（別フレーム）で配置しても、表示件数が同じで「ページごとに変える」という事が出来ない。

例えば、ブログページには１０件表示したいけど、トップページでは1件でいい（邪魔だから）という事が出来るといい。

**Comment by nagasheep** [comment]
賛成です。
なんか、この話、したこたあるような。
デジャビュなう。

**Comment by masaton0216** [comment]
やったれやったれ～（移行migrationも併せて対応が必要ですね）

**Comment by osws-makino** [comment]
表示件数を持たせるテーブルが変わるんですよね？
マイグレか……データ壊しそうで怖い……

**Comment by osws-makino** [comment]
PR：【ブログ】表示件数をフレームごとに設定できるようにする
こちらで対応されたので、この件はクローズします。
