### ISSUE TITLE
キャビネットで表示するファイル名はuploads テーブルから持ってきて欲しい。

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#58]
現在、キャビネットで表示するファイル名は以下かなと思います。
https://github.com/opensource-workshop/connect-cms/blob/master/database/migrations/2021_06_01_114533_create_cabinet_contents.php#L21

これを、以下から表示するようにして欲しい。
https://github.com/opensource-workshop/connect-cms/blob/master/database/migrations/2019_04_06_101735_create_uploads_table.php#L18

理由として、管理機能のアップロードファイル管理で、ファイル名の変更ができるのです。
で、変更したファイル名をキャビネットでも反映したいのです。

フォルダ名は、uploads テーブルにはないので、キャビネットのテーブルを使って欲しい。

**Comment by gakigaki** [comment]
対応しました！
