### ISSUE TITLE
【施設予約】複数日にまたがって予約したい

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms-ideas#67]
- 単日予約しかできない為、一定の期間等、日付をまたいだ予約をしたい時はその日付分の単日予約を行う必要がある。
- 終了日を設定できるといいかも？
- 現状のUIでは時間（From、End）しか設定できない為、改修する場合はUI、及び、内部処理は結構変更する必要がありそう。

**Comment by akagane99** [comment]
![image](https://github.com/user-attachments/assets/666c3fda-910d-4771-9da1-4d7edebf339c)
繰り返しパターンにより、柔軟に予約日を設定できるようになっていたため、本件はクローズします。
