### ISSUE TITLE
【セキュリティ管理】各IPの設定の部分に、コメントが書けるような欄が欲しい

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms-ideas#70]
各IPの設定の部分に、コメントが書けるような欄が欲しい

**Comment by masaton0216** [comment]
少し時間が空いたので対応しました。
![image](https://user-images.githubusercontent.com/13323806/132803383-83ab3ebb-4c3c-481d-80ec-d0afeab8cd38.png)
