### ISSUE TITLE
アップロードファイルの削除機能

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms-ideas#73]
wysiwig画面で旧ファイルへのリンクを削除 → 新ファイルをアップロード という流れの為、旧ファイルを削除する機能が存在しない。
サーバにあるリンクされていないファイルを削除する方法を検討する。
・ファイル一覧のような画面から手動で削除
・バッチによる定期的な削除などなど

**Comment by nagasheep** [comment]
再オープン。
- ファイル管理の詳細画面に「削除」ボタンを追加。
- ファイルは物理削除
- uploadsレコードは論理削除にしたい。（deleted_at を追加）
- 論理削除されたupload_id を指定されたダウンロードは、404 を返す。
![image](https://user-images.githubusercontent.com/3079435/132457668-6d79b21c-c4f9-447f-8e67-7fb96ea060ef.png)

**Comment by masaton0216** [comment]
[TODO]ファイル管理から問答無用で削除後、個別プラグインの挙動を確認する。
- キャビネット
- フォトアルバム

**Comment by masaton0216** [comment]
下記のPRで検討した結果、uploadsのレコード削除は物理削除に方針変更しました。
論理削除の検討余地はありますが、本Issueの内容はほぼ実装済みの為、本Issueはcloseとします。
https://github.com/opensource-workshop/connect-cms/pull/1546
