### ISSUE TITLE
【ウィジウィグ】オリジナルの画像アップロードダイアログ

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#74]
仕様イメージは以下
実装方法など、調整しながらやっていきたい。

---
![image](https://user-images.githubusercontent.com/3079435/132463862-2c65d314-9f62-4765-9623-bae8de7981b3.png)

**Comment by nagasheep** [comment]
【現状のTinyMCEをカスタマイズする案】
とりあえず、画面をカスタマイズしてみた。
<img src="https://user-images.githubusercontent.com/3079435/132628035-bdf8bb55-d04c-45a4-a05b-81808d1f5650.png" width="500">
<img src="https://user-images.githubusercontent.com/3079435/132628221-6071fe38-def9-4967-9a2d-72c5e4648088.png" width="500">

**Comment by nagasheep** [comment]
画像サイズの設定値は、サイト毎に異なる可能性もありので、TinyMCEにパラメータで渡したい。
image_class_list を渡しているところが参考になりそう。

**Comment by nagasheep** [comment]
画像サイズの設定値は、アップロード時のみ、有効となる仕様のため、編集画面では画像サイズのリストボックスは非表示にしたい。
編集時というのが、TinyMCEのプラグイン内で、プロパティなど持っていればよいけど、無い場合は、画面を開いた時の画像のソースを見て、値があれば編集時。という判断もアリかな。

**Comment by akagane99** [comment]
下記で対応済み。
* https://github.com/opensource-workshop/connect-cms-ideas/issues/15#issuecomment-929848095
