### ISSUE TITLE
スライダー・プラグイン

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#8]
作ること。

**Comment by nagasheep** [comment]
以前のIssue も参考に。
https://github.com/opensource-workshop/connect-cms/issues/446
- 画像の複数アップ、削除機能
- インジケータとコントローラのデザイン調整機能

**Comment by masaton0216** [comment]
@nagasheep 着手しようと思うんですが、プラグイン名ってNC2に倣ってスライダーの方がいいですか？Bootstrapに倣うならカルーセルになると思うのですが、nc2の馴染みに配慮するか否か🤔

**Comment by nagasheep** [comment]
悩ましいね。
NC2 のスライダーも、NC2 標準のモジュールにはなく、永原が作ったものなのよね。
その当時は、「スライダー」という名称が一般のユーザにとってわかりやすいかなと思って。
何がわかりやすいのかな。＆ それをどうすれば、確認できるんだろうなぁ。

**Comment by nagasheep** [comment]
Google 検索、Google Trend からは、スライダーの方が、一般的ではないかと思える。
![image](https://user-images.githubusercontent.com/3079435/119061364-2b613a00-ba0f-11eb-8261-622b2d643ce5.png)
![image](https://user-images.githubusercontent.com/3079435/119061390-387e2900-ba0f-11eb-884e-21da5100d101.png)
![image](https://user-images.githubusercontent.com/3079435/119061410-4338be00-ba0f-11eb-9053-39a1668ea4f9.png)

**Comment by nagasheep** [comment]
「スライドショー」というのも、アリなのかも。
http://www.3s-sys.co.jp/blog/2016/11/29/802/

**Comment by nagasheep** [comment]
写真の「スライドショー」にリンクの機能がある。という考え方も、違和感はないのよね。

**Comment by nagasheep** [comment]
「カルーセル」という単語より、「スライドショー」の方が、単語から意味が伝わりやすいのではないかと思えるので、「スライドショー」に1票です。

**Comment by masaton0216** [comment]
- スライダー：Webのグリグリ動かせるUIと被る。そういったUIが今後追加される可能性が多分にあるので、コミュニティの掲示板等でやり取りする際に誤認の可能性もあるので×
- カルーセル：Bootstrapに触れてる人なら連想できそうですが、利用層視点で見ると一般的ではないので×
- スライドショー：認知層の多そうなパワポでも採用されているネーミングで、CMSと組み合わさった時にどういった機能かも比較的イメージはしやすい気がします。ということでスライドショー賛成です。

**Comment by masaton0216** [comment]
構想残
- [ ] 項目設定画面が窮屈。項目によっては見切れている。
- [ ] スライダーの写真に期限が設定できるようにしたい
https://github.com/opensource-workshop/connect-cms/issues/472
- [ ] スライドショー設定画面にスライドショーのプレビュー（コントローラ／インジケータ／フェードOnOff／インターバル変更時）機能
- [ ] スライドショー設定画面のコントローラ／インジケータのデザイン（色／サイズ／形）機能

**Comment by kousei86** [comment]
待望のスライダーを使ってみました。
ありがとうございます。

以下を報告いたします。
－－－－－－－－－－－－－－－－－－

【背景】
現在、さくらのレンタルサーバーでのインストール手順に従い、
/test01/ のシンボリックリンクを付けてConnect-CMSを使っています。

【問題】
スライドショーの**画像がリンク切れ**を起こしている。

【きっと原因は･･･】
さくらのレンタルサーバー用のインストール手順に従うと、
シンボリックリンク「test01」のためにリンクのパスが合わなくなる。

【検証情報】
○ 「スライドショーの画像選択」画面で表示されるサムネイル画像のimg要素
　<img src="https://goodtrials.jpn.org/**kousei86/test01/file/30**" width="100px">

○ 「該当のページ」でリンク切れで表示されているスライドショー画像のimg要素
　<img **src="/file/30"** class="d-block w-100">

　なお、この 「file/30」の前に「 /kousei86/test01/ 」を挟むと、
　設定した画像が表示されるようになる。（ブラウザの開発者ツールを使って検証した）

－－－－－－－－－－－－－－－－－－

以上、ご確認ください。

**Comment by kousei86** [comment]
待望のスライダーを使ってみました。
ありがとうございます。

以下を報告いたします。
－－－－－－－－－－－－－－－－－－

【背景】
現在、さくらのレンタルサーバーでそれ用のインストール手順に従い、
/test01/ のシンボリックリンクを付けてConnect-CMSを使っています。

【問題】
スライドショーの画像がリンク切れを起こしている。

【きっと原因は･･･】
さくらのレンタルサーバー用のインストール手順に従うと、
シンボリックリンク「test01」のために画像ファイルへのパスが合わなくなる。

【検証情報】
○ 「スライドショーの画像選択」画面で表示されているサムネイル画像のimg要素（← ブラウザのソースコードを確認）
　〈img src="https://goodtrials.jpn.org/kousei86/test01/file/30" width="100px"〉

○ 「スライドショープラグインを配置したページ」で設定されている画像のimg要素（ → リンク切れで表示されていない ）
　〈img src="/file/30" class="d-block w-100"〉

　この 「/file/30」の前に「 /kousei86/test01 」を挟むと、設定した画像が表示されるようになりました。
　（↑ ブラウザの開発者ツールを使って検証した）

－－－－－－－－－－－－－－－－－－

以上、ご確認ください。

**Comment by masaton0216** [comment]
@kousei86 
ご無沙汰しております。

早速のご使用＆フィードバック頂きありがとうございます。
プログラムがディレクトリインストール時用のお作法に則ってなかった為、修正をかけました。
手元にディレクトリインストール環境がない為、未検証のところを誠に恐縮ですが、ご確認を頂けますでしょうか？

**Comment by kousei86** [comment]
はい、修正を確認しました。
スライダープラグインで指定した画像が表示されるようになりました。
夜分遅くにも関わらず、ありがとうございます。

**Comment by gakigaki** [comment]
対応済みのためクローズ。
構想残は本体のissueに移す。
