### ISSUE TITLE
リンクリストのURL項目を255より長くしたい。

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#80]
公式サイトに挙がった以下の件への対応。
https://connect-cms.jp/plugin/bbses/show/106/233/434#frame-233

**Comment by nagasheep** [comment]
----------------------------------------
- 仕様の確認から
----------------------------------------

--- RFC の該当URL

https://datatracker.ietf.org/doc/html/rfc2616#section-3.2.1

--- RFC 2616 のURL（URI）の長さに関する記述

The HTTP protocol does not place any a priori limit on the length of
a URI. Servers MUST be able to handle the URI of any resource they
serve, and SHOULD be able to handle URIs of unbounded length if they
provide GET-based forms that could generate such URIs. A server
SHOULD return 414 (Request-URI Too Long) status if a URI is longer

--- 和訳

https://triple-underscore.github.io/rfc-others/RFC2616-ja.html#section-3.2

HTTP プロトコルでは、URI の長さにどんな制限も設けていない。 サーバは、自身が持つどんなリソースの URI も扱えなければならないし、もしそのような URI を生成する GET ベースのフォームを用意するなら、無制限の長さの URI を扱えるべきである。 もし、その URI がサーバが処理できるものよりも長ければ、サーバは 414 (Request-URI Too Long) ステータスを返すべきである (section 10.4.15 参照)。
--- 仕様の確認まとめ

仕様的には長さの制限はない。
しかし、実装方法（データベース定義）やセキュリティの考慮、環境（Webサーバなど）面から、実質的な制限を検討する。

----------------------------------------
- 環境
----------------------------------------

--- ブラウザ
IEなら 2,083 文字らしい。
https://support.microsoft.com/ja-jp/topic/url-%E3%81%AE%E6%9C%80%E5%A4%A7%E9%95%B7%E3%81%AF-2-083-%E6%96%87%E5%AD%97internet-explorer-174e7c8a-6666-f4e0-6fd6-908b53c12246

--- Apache のLimitRequestLine ディレクティブ
http://httpd.apache.org/docs/2.4/mod/core.html#limitrequestline
デフォルトが 8190 バイト。
ここに合わせたい。

制限する意味は、LimitRequestLine ディレクティブの以下の説明の通り。
「このディレクティブは、 管理者にクライアントからの異常なリクエストを制御できるようにし、 何らかの形のサービス拒否攻撃 (訳注:DoS) を避けるのに有効です。」

----------------------------------------
- Connect-CMS
----------------------------------------

--- 対象テーブル
pages の othersite_url
linklist_posts の url
slideshows_items の link_url

--- 現在の型
varchar(255) utf8mb4_general_ci

----------------------------------------
- その他注意点
----------------------------------------

--- MySQL のインデックス長の問題が影響しないか。
URL 項目にインデックスを作成しないつもりなので、問題なし。

**Comment by nagasheep** [comment]
悩ましい子がいてた。
pagesテーブルのpermanent_link。（ページの固定リンク）

以下のようにしようと思う。
現状、varchar(255) だが、URL 項目ということで、varchar(8190) にする。
ただし、エラーチェック時は独自のチェックとして、APP_URL ＋ permanent_link が8190 バイト以内かでチェックする。

**Comment by akagane99** [comment]
memo：関連issue
* https://github.com/opensource-workshop/connect-cms/issues/879
* https://github.com/opensource-workshop/connect-cms/issues/787

**Comment by nagasheep** [comment]
--- MySQL の「最大行サイズは 65,535 バイト」の制約について。

以下のマニュアルの通り、MySQL の「最大行サイズは 65,535 バイト」の制約があるため、URL 項目として持とうとしていた varchar(8190)、Laravel では string('culumn_name', 8190) について。
8190 は文字数であり、最大行サイズは 65,535 バイトとなると、varchar で大きな値を使うことは、今後のテーブルの拡張を考えた際に、良くないという考えに至りました。
そのため、URL 項目は、TEXT 型を使用します。
TEXT 型の場合は、行サイズに与える影響は少ないためです。
行サイズに与える影響の詳細は以下のマニュアルの抜粋を参照。

以下、MySQL マニュアルからの抜粋です。

MySQL 5.6 リファレンスマニュアル  /  制約と制限  /  MySQL での制限  /  テーブルカラム数と行サイズの制限
D.10.4 テーブルカラム数と行サイズの制限
https://dev.mysql.com/doc/refman/5.6/ja/column-count-limit.html

すべてのテーブル (ストレージエンジンには無関係) の最大行サイズは 65,535 バイトです。ストレージエンジンではこの制限に対してさらなる制約を加えられる場合があり、有効な最大行サイズは少なくなります。

BLOB カラムと TEXT カラムは、その内容が行の残りとは別に格納されるので、行サイズに対してそれぞれ 9 から 12 (1から4+8) バイトになります。

**Comment by nagasheep** [comment]
完了
