### ISSUE TITLE
WYSIWYG 項目の文字列長チェックについて

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms-ideas#82]
WYSIWYG 項目の文字列長を共通処理にしたい。

--- ポイント

Connect-CMS では、現在、WYSIWYG 項目をMySQL のtext 型で表しています。
text 型の「バイト数制限」及び、混在した文字列から、utf8mb4 を意識した文字のバイト数を取れるかがポイントになります。

--- MySQL

text型
保存できる文字数は 65,535バイトまで。
英数字であれば、65,535文字格納できます。

実際の格納した値をLENGTH 関数でSQL 実行すると、
・英数字：1バイト
・日本語：3バイト
・絵文字：4バイト
になっていることが確認できた。

--- PHP

英数字、日本語、絵文字が混在する文字列のバイト数を確認する。
strlen 関数がイケた。

echo strlen("12");    ⇒ 2
echo strlen("あい");  ⇒ 6
echo strlen("1あい"); ⇒ 7
echo strlen("👍");    ⇒ 4

--- Laravel

Laravel の max バリデーションは、mb_strlen を呼ぶので、これではダメ。

// 参考
max 関数の実体
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1216

サイズチェック関数
https://github.com/laravel/framework/blob/568e74170659bc38d0cfcbb1d6006b437d55feb0/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1958

mb_strlen 使用
https://github.com/laravel/framework/blob/568e74170659bc38d0cfcbb1d6006b437d55feb0/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1974

ということで、バリデーションを追加する方向で考えようと思う。
バリデーション名は以下かな。
wysiwyg_max

**Comment by akagane99** [comment]
> ということで、バリデーションを追加する方向で考えようと思う。
バリデーション名は以下かな。
wysiwyg_max

* https://github.com/opensource-workshop/connect-cms-ideas/issues/80

上記URLでも同様にバイトチェックが必要になると思うのですが、どうなんでしょ？
日本語URLで、URLのインプットに日本語混在するかなと。

そうであれば、汎用的にバリデーション名 byte とかかなぁと。
wysiwyg_max の最大値は Const でとっかに持つとかで。

**Comment by nagasheep** [comment]
なるほど。varchar でも、絵文字入れたらどうなるか。
試してみよう。

**Comment by nagasheep** [comment]
varchar でも、絵文字入れたらどうなるか。
試してみました。

varchar の場合の指定は、「文字数」のようで、varchar(255) に絵文字 255 文字、入りました。
その場合の LENGTH 関数での数値は 1,020。4×255 の値ですね。
ローカルで絵文字を 256 文字入れたら、1文字、切り捨てられて、255 文字になりました。

どうも、varchara 型とtext 型では、動きが違うようですね。
もう少し、MySQL のドキュメントを見てみます。

**Comment by nagasheep** [comment]
https://dev.mysql.com/doc/refman/5.6/ja/string-type-overview.html

以下、varchar の説明部分
`可変長文字列です。M はカラムの最大長を文字数で表します。M の範囲は 0 から 65,535 です。VARCHAR の有効な最大長は、最大行サイズ (65,535 バイト、すべてのカラムで共有されます) と使用される文字セットによって決まります。たとえば、utf8 の文字は 1 文字につき最大 3 バイトを必要とする場合があるため、utf8 の文字セットを使用する VARCHAR カラムは、最大 21,844 文字になるように宣言できます。
`

「カラムの最大長を文字数で表します。」
「utf8 の文字セットを使用する VARCHAR カラムは、最大 21,844 文字になるように宣言できます。」
この辺の文言がヒントかなという気がする。

varchar 型は、「文字数」で指定するみたいね。
で、バイト数は、最大 65,535 バイト。これは、指定できるわけではないけど、MySQL 側で管理しているんだろうね。

text 型
`「値にマルチバイト文字が含まれる場合、有効な最大長は少なくなります。」`
ここがヒントかな。

varchar 型は、text 型の文字数指定しているもの。みたいな感じなのかもね。

久しぶりにちゃんと勉強した気がする（笑）

**Comment by nagasheep** [comment]
エラー画面のイメージ
![image](https://user-images.githubusercontent.com/3079435/135948084-125e05b3-45e4-478d-aa61-5e1d11d1346f.png)

**Comment by nagasheep** [comment]
以下のブランチにアップロードしました。
https://github.com/opensource-workshop/connect-cms/tree/Validation

**Comment by akagane99** [comment]
メモ：修正内容
https://github.com/opensource-workshop/connect-cms/compare/Validation

関連issue
* https://github.com/opensource-workshop/connect-cms/issues/879
* https://github.com/opensource-workshop/connect-cms/issues/787

・validateはカスタムバリデートにもってく
・入力エラー表示は、共通部品を使うよう修正する。
・ウィジウィグのエラー補足は共通部品化する。

**Comment by akagane99** [comment]
> * https://github.com/opensource-workshop/connect-cms/issues/787
>
> ・validateはカスタムバリデートにもってく
・入力エラー表示は、共通部品を使うよう修正する。
・ウィジウィグのエラー補足は共通部品化する。

上記対応しました。

修正内容
https://github.com/opensource-workshop/connect-cms/compare/Validation

**Comment by akagane99** [comment]
掲示板を試し対応していましたが、
手元の開発環境では、掲示板の記事のDB型は実際は`mediumtext`でした。
他、固定記事、ブログも同様でした。

![image](https://user-images.githubusercontent.com/2756509/136489915-8ed88854-c9bf-47da-8d65-0499fa70af03.png)

`mediumtext`は最大長が 16,777,215 (224 − 1) 文字の TEXT カラムのため、65,535バイトまでチェックとずれていました。
https://dev.mysql.com/doc/refman/5.6/ja/string-type-overview.html

チェックの見直しが必要そうです。

対応案）
16,777,215 バイトまで広げる？

**Comment by akagane99** [comment]
どうも環境によってtext型のサイトと、mediumtext型のサイトがあった。

・最近インストールしたサイト：text型
　・DBテーブルの違い：オプション row_format=DYNAMIC だとtext型（これが影響？）
・昔にインストールしたサイト：mediumtext型
　・DBテーブルの違い：オプション未指定だとmediumtext型（これが影響？）

※ row_format=DYNAMIC 対応は、utf8mb4対応で入った。
https://github.com/opensource-workshop/connect-cms/commit/622386a6cb7b7f150f064f3934ba42d9e8d0b1a2

⇒ 最近インストールした際とはtext型のため、WYSIWYGはtext型想定で進めます。
　そのため、65,535バイトまでチェックでOK。
