### ISSUE TITLE
【フォーム】登録済みデータを一括削除する処理か、項目コピー機能が欲しい

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms-ideas#89]
フォームについて、登録済みデータを一括削除する処理か、別フォームの項目一括コピー機能が欲しい

【理由】
毎年同じ質問をするフォームを使いまわしたいから
いちいち項目を新規で作り直すのも面倒なので。

**Comment by akagane99** [comment]
フォームのコピー機能が対応済みなので、クローズします。
