### ISSUE TITLE
サイト内検索の検索対象に、掲示板プラグインを追加する

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms-ideas#9]
（connect-cms公式サイトのフォーラムからの転記です）

connect-cms公式サイトのフォーラムに投稿も増えてきて、過去に既に似たような質問があるかどうか探すのに時間がかかるようになってきています。
そのため、サイト内検索に、掲示板（フォーラム）プラグインも検索対象にできれば、便利かと思います。

**Comment by gakigaki** [comment]
対応済みのため、クローズします。
